import { useEffect, useState } from 'react';

interface Workshop {
  id: string;
  title: string;
  aiSummary: string | null;
  status: string;
}

const WorkshopDetails = ({ workshopId }: { workshopId: string }) => {
  const [workshop, setWorkshop] = useState<Workshop | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchWorkshop = async () => {
      try {
        const response = await fetch(`http://localhost:3000/workshops/${workshopId}`);
        if (response.ok) {
          const data = await response.json();
          setWorkshop(data);
        }
      } catch (error) {
        console.error('Failed to fetch workshop', error);
      } finally {
        setLoading(false);
      }
    };

    fetchWorkshop();
    
    // Poll for summary every 5 seconds if it's missing
    const interval = setInterval(() => {
      if (workshop && !workshop.aiSummary) {
        fetchWorkshop();
      }
    }, 5000);

    return () => clearInterval(interval);
  }, [workshopId, workshop?.aiSummary]);

  if (loading) return (
    <div className="max-w-4xl mx-auto mt-10 p-8 bg-white rounded-3xl shadow-xl border border-gray-100 animate-pulse">
      <div className="h-10 bg-gray-200 rounded-lg w-3/4 mb-4"></div>
      <div className="h-6 bg-gray-100 rounded-lg w-1/4 mb-10"></div>
      <div className="h-48 bg-indigo-50 rounded-2xl"></div>
    </div>
  );

  if (!workshop) return (
    <div className="max-w-4xl mx-auto mt-10 p-12 bg-red-50 rounded-3xl border border-red-100 text-center">
      <div className="text-red-500 text-5xl mb-4">⚠️</div>
      <h2 className="text-2xl font-bold text-red-900 mb-2">Workshop not found</h2>
      <p className="text-red-600">The workshop you're looking for doesn't exist or has been removed.</p>
    </div>
  );

  return (
    <div className="p-8 max-w-4xl mx-auto bg-white rounded-3xl shadow-2xl border border-gray-50 mt-10 transition-all hover:shadow-indigo-100">
      <div className="flex justify-between items-start mb-8">
        <div>
          <h1 className="text-4xl font-black text-gray-900 tracking-tight mb-3">{workshop.title}</h1>
          <span className={`inline-flex items-center px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-widest shadow-sm
            ${workshop.status === 'active' ? 'bg-emerald-100 text-emerald-700 border border-emerald-200' : 'bg-rose-100 text-rose-700 border border-rose-200'}`}>
            <span className={`w-2 h-2 rounded-full mr-2 ${workshop.status === 'active' ? 'bg-emerald-500' : 'bg-rose-500'} animate-pulse`}></span>
            {workshop.status}
          </span>
        </div>
      </div>

      <div className="space-y-8">
        <section className="relative overflow-hidden p-8 rounded-2xl bg-gradient-to-br from-indigo-50 via-white to-blue-50 border border-indigo-100 shadow-inner">
          <div className="absolute top-0 right-0 -mt-10 -mr-10 w-40 h-40 bg-indigo-400/10 rounded-full blur-3xl"></div>
          <div className="absolute bottom-0 left-0 -mb-10 -ml-10 w-32 h-32 bg-blue-400/10 rounded-full blur-3xl"></div>
          
          <h2 className="flex items-center text-sm font-black text-indigo-900 mb-6 uppercase tracking-[0.2em]">
            <span className="p-2 bg-indigo-600 rounded-lg mr-3 shadow-lg shadow-indigo-200">
              <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </span>
            AI Content Summary
          </h2>
          
          {workshop.aiSummary ? (
            <div className="relative">
              <span className="absolute -top-4 -left-2 text-6xl text-indigo-200 font-serif opacity-50">“</span>
              <p className="text-gray-700 leading-relaxed text-xl font-medium relative z-10 px-4">
                {workshop.aiSummary}
              </p>
              <div className="flex justify-end mt-4">
                <span className="text-xs font-bold text-indigo-400 uppercase tracking-widest">Generated by UniHub AI</span>
              </div>
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <div className="relative">
                <div className="w-16 h-16 border-4 border-indigo-100 border-t-indigo-600 rounded-full animate-spin"></div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="w-2 h-2 bg-indigo-600 rounded-full animate-ping"></div>
                </div>
              </div>
              <p className="text-indigo-900 font-black text-xl mt-6 tracking-tight">
                Synthesizing document...
              </p>
              <p className="text-gray-500 text-sm mt-2 font-medium">This usually takes about 30 seconds to provide the best summary.</p>
            </div>
          )}
        </section>
      </div>
    </div>
  );
};

export default WorkshopDetails;
